export enum Pass {
    PASS_DAY = "PASS_DAY",
    PASS_WEEKEND = "PASS_WEEKEND",
    PASS_YEAR = "PASS_YEAR",
    PASS_DAYMONTH = "PASS_DAYMONTH",
    PASS_ESCAPEGAME = "PASS_ESCAPEGAME",
    PASS_NIGHT = "PASS_NIGHT"
}